# Site settings
title: Katy Bowman
email: katybowman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web development portfolio site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.k80bowman.com" # the base hostname & protocol for your site
twitter_username: k80bowman
github_username:  k80bowman

# Build settings
markdown: kramdown
